%YAML 1.1
---
# pre-commit Framework Configuration
# https://pre-commit.com/
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yaml|yml|yamllint)$
...
